# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keypadWith.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(8, 290, 291, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_Back = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Back.sizePolicy().hasHeightForWidth())
        self.pushButton_Back.setSizePolicy(sizePolicy)
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.gridLayout.addWidget(self.pushButton_Back, 3, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_Clear = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Clear.sizePolicy().hasHeightForWidth())
        self.pushButton_Clear.setSizePolicy(sizePolicy)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.gridLayout.addWidget(self.pushButton_Clear, 3, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(8, 220, 291, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_Scan = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Scan.sizePolicy().hasHeightForWidth())
        self.pushButton_Scan.setSizePolicy(sizePolicy)
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.gridLayout_2.addWidget(self.pushButton_Scan, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_Image_Bus = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Bus.setGeometry(QtCore.QRect(318, 120, 451, 461))
        self.label_Image_Bus.setStyleSheet("image: url(:/newPrefix/Images/bustyres.png);")
        self.label_Image_Bus.setText("")
        self.label_Image_Bus.setObjectName("label_Image_Bus")
        self.label_Image_Press_RLI = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Press_RLI.setGeometry(QtCore.QRect(329, 460, 51, 61))
        self.label_Image_Press_RLI.setStyleSheet("image: url(:/newPrefix/Images/pressure.png);")
        self.label_Image_Press_RLI.setText("")
        self.label_Image_Press_RLI.setObjectName("label_Image_Press_RLI")
        self.label_Image_Temp_RLI = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Temp_RLI.setGeometry(QtCore.QRect(388, 470, 61, 51))
        self.label_Image_Temp_RLI.setStyleSheet("image: url(:/newPrefix/Images/temp.png);")
        self.label_Image_Temp_RLI.setText("")
        self.label_Image_Temp_RLI.setObjectName("label_Image_Temp_RLI")
        self.label_Image_Temp_RRI = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Temp_RRI.setGeometry(QtCore.QRect(700, 470, 61, 51))
        self.label_Image_Temp_RRI.setStyleSheet("image: url(:/newPrefix/Images/temp.png);")
        self.label_Image_Temp_RRI.setText("")
        self.label_Image_Temp_RRI.setObjectName("label_Image_Temp_RRI")
        self.label_Image_Press_RRI = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Press_RRI.setGeometry(QtCore.QRect(638, 460, 51, 61))
        self.label_Image_Press_RRI.setStyleSheet("image: url(:/newPrefix/Images/pressure.png);")
        self.label_Image_Press_RRI.setText("")
        self.label_Image_Press_RRI.setObjectName("label_Image_Press_RRI")
        self.label_Image_Temp_RLO = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Temp_RLO.setGeometry(QtCore.QRect(389, 350, 61, 51))
        self.label_Image_Temp_RLO.setStyleSheet("image: url(:/newPrefix/Images/temp.png);")
        self.label_Image_Temp_RLO.setText("")
        self.label_Image_Temp_RLO.setObjectName("label_Image_Temp_RLO")
        self.label_Image_Press_RRO = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Press_RRO.setGeometry(QtCore.QRect(639, 340, 51, 61))
        self.label_Image_Press_RRO.setStyleSheet("image: url(:/newPrefix/Images/pressure.png);")
        self.label_Image_Press_RRO.setText("")
        self.label_Image_Press_RRO.setObjectName("label_Image_Press_RRO")
        self.label_Image_Press_RLO = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Press_RLO.setGeometry(QtCore.QRect(330, 340, 51, 61))
        self.label_Image_Press_RLO.setStyleSheet("image: url(:/newPrefix/Images/pressure.png);")
        self.label_Image_Press_RLO.setText("")
        self.label_Image_Press_RLO.setObjectName("label_Image_Press_RLO")
        self.label_Image_Temp_RRO = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Temp_RRO.setGeometry(QtCore.QRect(700, 350, 61, 51))
        self.label_Image_Temp_RRO.setStyleSheet("image: url(:/newPrefix/Images/temp.png);")
        self.label_Image_Temp_RRO.setText("")
        self.label_Image_Temp_RRO.setObjectName("label_Image_Temp_RRO")
        self.label_Image_Temp_FL = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Temp_FL.setGeometry(QtCore.QRect(389, 180, 61, 51))
        self.label_Image_Temp_FL.setStyleSheet("image: url(:/newPrefix/Images/temp.png);")
        self.label_Image_Temp_FL.setText("")
        self.label_Image_Temp_FL.setObjectName("label_Image_Temp_FL")
        self.label_Image_Press_FR = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Press_FR.setGeometry(QtCore.QRect(639, 170, 51, 61))
        self.label_Image_Press_FR.setStyleSheet("image: url(:/newPrefix/Images/pressure.png);")
        self.label_Image_Press_FR.setText("")
        self.label_Image_Press_FR.setObjectName("label_Image_Press_FR")
        self.label_Image_Press_FL = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Press_FL.setGeometry(QtCore.QRect(330, 170, 51, 61))
        self.label_Image_Press_FL.setStyleSheet("image: url(:/newPrefix/Images/pressure.png);")
        self.label_Image_Press_FL.setText("")
        self.label_Image_Press_FL.setObjectName("label_Image_Press_FL")
        self.label_Image_Temp_FR = QtWidgets.QLabel(self.centralwidget)
        self.label_Image_Temp_FR.setGeometry(QtCore.QRect(700, 180, 61, 51))
        self.label_Image_Temp_FR.setStyleSheet("image: url(:/newPrefix/Images/temp.png);")
        self.label_Image_Temp_FR.setText("")
        self.label_Image_Temp_FR.setObjectName("label_Image_Temp_FR")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(328, 110, 421, 531))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_Psi1 = QtWidgets.QLabel(self.groupBox)
        self.label_Psi1.setGeometry(QtCore.QRect(60, 90, 21, 16))
        self.label_Psi1.setObjectName("label_Psi1")
        self.label_Psi3 = QtWidgets.QLabel(self.groupBox)
        self.label_Psi3.setGeometry(QtCore.QRect(60, 260, 21, 16))
        self.label_Psi3.setObjectName("label_Psi3")
        self.label_Psi5 = QtWidgets.QLabel(self.groupBox)
        self.label_Psi5.setGeometry(QtCore.QRect(60, 380, 21, 16))
        self.label_Psi5.setObjectName("label_Psi5")
        self.label_Psi2 = QtWidgets.QLabel(self.groupBox)
        self.label_Psi2.setGeometry(QtCore.QRect(370, 90, 21, 16))
        self.label_Psi2.setObjectName("label_Psi2")
        self.label_Psi4 = QtWidgets.QLabel(self.groupBox)
        self.label_Psi4.setGeometry(QtCore.QRect(370, 260, 21, 16))
        self.label_Psi4.setObjectName("label_Psi4")
        self.label_Psi6 = QtWidgets.QLabel(self.groupBox)
        self.label_Psi6.setGeometry(QtCore.QRect(370, 380, 21, 16))
        self.label_Psi6.setObjectName("label_Psi6")
        self.label_FLText = QtWidgets.QLabel(self.groupBox)
        self.label_FLText.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_FLText.setObjectName("label_FLText")
        self.label_FRText = QtWidgets.QLabel(self.groupBox)
        self.label_FRText.setGeometry(QtCore.QRect(310, 50, 81, 16))
        self.label_FRText.setObjectName("label_FRText")
        self.label_RLOText = QtWidgets.QLabel(self.groupBox)
        self.label_RLOText.setGeometry(QtCore.QRect(10, 220, 111, 16))
        self.label_RLOText.setObjectName("label_RLOText")
        self.label_RLIText = QtWidgets.QLabel(self.groupBox)
        self.label_RLIText.setGeometry(QtCore.QRect(10, 340, 111, 16))
        self.label_RLIText.setObjectName("label_RLIText")
        self.label_RRIText = QtWidgets.QLabel(self.groupBox)
        self.label_RRIText.setGeometry(QtCore.QRect(310, 340, 121, 16))
        self.label_RRIText.setObjectName("label_RRIText")
        self.label_RROText = QtWidgets.QLabel(self.groupBox)
        self.label_RROText.setGeometry(QtCore.QRect(310, 220, 121, 16))
        self.label_RROText.setObjectName("label_RROText")
        self.lineEdit_FLPress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FLPress.setGeometry(QtCore.QRect(0, 120, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FLPress.sizePolicy().hasHeightForWidth())
        self.lineEdit_FLPress.setSizePolicy(sizePolicy)
        self.lineEdit_FLPress.setObjectName("lineEdit_FLPress")
        self.lineEdit_FLTemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FLTemp.setGeometry(QtCore.QRect(70, 120, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FLTemp.sizePolicy().hasHeightForWidth())
        self.lineEdit_FLTemp.setSizePolicy(sizePolicy)
        self.lineEdit_FLTemp.setObjectName("lineEdit_FLTemp")
        self.lineEdit_FRPress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FRPress.setGeometry(QtCore.QRect(290, 120, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FRPress.sizePolicy().hasHeightForWidth())
        self.lineEdit_FRPress.setSizePolicy(sizePolicy)
        self.lineEdit_FRPress.setObjectName("lineEdit_FRPress")
        self.lineEdit_FRTemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FRTemp.setGeometry(QtCore.QRect(360, 120, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FRTemp.sizePolicy().hasHeightForWidth())
        self.lineEdit_FRTemp.setSizePolicy(sizePolicy)
        self.lineEdit_FRTemp.setObjectName("lineEdit_FRTemp")
        self.lineEdit_RLOPress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RLOPress.setGeometry(QtCore.QRect(0, 290, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RLOPress.sizePolicy().hasHeightForWidth())
        self.lineEdit_RLOPress.setSizePolicy(sizePolicy)
        self.lineEdit_RLOPress.setObjectName("lineEdit_RLOPress")
        self.lineEdit_RLOTemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RLOTemp.setGeometry(QtCore.QRect(70, 290, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RLOTemp.sizePolicy().hasHeightForWidth())
        self.lineEdit_RLOTemp.setSizePolicy(sizePolicy)
        self.lineEdit_RLOTemp.setObjectName("lineEdit_RLOTemp")
        self.lineEdit_RROPress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RROPress.setGeometry(QtCore.QRect(290, 290, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RROPress.sizePolicy().hasHeightForWidth())
        self.lineEdit_RROPress.setSizePolicy(sizePolicy)
        self.lineEdit_RROPress.setObjectName("lineEdit_RROPress")
        self.lineEdit_RROTemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RROTemp.setGeometry(QtCore.QRect(360, 290, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RROTemp.sizePolicy().hasHeightForWidth())
        self.lineEdit_RROTemp.setSizePolicy(sizePolicy)
        self.lineEdit_RROTemp.setObjectName("lineEdit_RROTemp")
        self.lineEdit_RLIPress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RLIPress.setGeometry(QtCore.QRect(0, 410, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RLIPress.sizePolicy().hasHeightForWidth())
        self.lineEdit_RLIPress.setSizePolicy(sizePolicy)
        self.lineEdit_RLIPress.setObjectName("lineEdit_RLIPress")
        self.lineEdit_RLITemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RLITemp.setGeometry(QtCore.QRect(70, 410, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RLITemp.sizePolicy().hasHeightForWidth())
        self.lineEdit_RLITemp.setSizePolicy(sizePolicy)
        self.lineEdit_RLITemp.setObjectName("lineEdit_RLITemp")
        self.lineEdit_RRIPress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RRIPress.setGeometry(QtCore.QRect(290, 420, 61, 20))
        self.lineEdit_RRIPress.setObjectName("lineEdit_RRIPress")
        self.lineEdit_RRITemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_RRITemp.setGeometry(QtCore.QRect(360, 420, 61, 20))
        self.lineEdit_RRITemp.setObjectName("lineEdit_RRITemp")
        self.label_Text_TPMS = QtWidgets.QLabel(self.centralwidget)
        self.label_Text_TPMS.setGeometry(QtCore.QRect(150, 20, 481, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Text_TPMS.sizePolicy().hasHeightForWidth())
        self.label_Text_TPMS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Text_TPMS.setFont(font)
        self.label_Text_TPMS.setObjectName("label_Text_TPMS")
        self.pushButton_Done = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Done.setGeometry(QtCore.QRect(100, 480, 101, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Done.sizePolicy().hasHeightForWidth())
        self.pushButton_Done.setSizePolicy(sizePolicy)
        self.pushButton_Done.setObjectName("pushButton_Done")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(380, 60, 311, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_BusNoText = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_BusNoText.sizePolicy().hasHeightForWidth())
        self.label_BusNoText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_BusNoText.setFont(font)
        self.label_BusNoText.setObjectName("label_BusNoText")
        self.horizontalLayout.addWidget(self.label_BusNoText)
        self.lineEdit_BusNo = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_BusNo.sizePolicy().hasHeightForWidth())
        self.lineEdit_BusNo.setSizePolicy(sizePolicy)
        self.lineEdit_BusNo.setObjectName("lineEdit_BusNo")
        self.horizontalLayout.addWidget(self.lineEdit_BusNo)
        self.layoutWidget.raise_()
        self.label_Image_Bus.raise_()
        self.groupBox.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_Image_Press_RLI.raise_()
        self.label_Image_Temp_RLI.raise_()
        self.label_Image_Temp_RRI.raise_()
        self.label_Image_Press_RRI.raise_()
        self.label_Image_Temp_RLO.raise_()
        self.label_Image_Press_RRO.raise_()
        self.label_Image_Press_RLO.raise_()
        self.label_Image_Temp_RRO.raise_()
        self.label_Image_Temp_FL.raise_()
        self.label_Image_Press_FR.raise_()
        self.label_Image_Press_FL.raise_()
        self.label_Image_Temp_FR.raise_()
        self.label_Text_TPMS.raise_()
        self.pushButton_Done.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_Back.setText(_translate("MainWindow", "Back<-"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_Clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_Scan.setText(_translate("MainWindow", "Scan"))
        self.label_Psi1.setText(_translate("MainWindow", "Psi"))
        self.label_Psi3.setText(_translate("MainWindow", "Psi"))
        self.label_Psi5.setText(_translate("MainWindow", "Psi"))
        self.label_Psi2.setText(_translate("MainWindow", "Psi"))
        self.label_Psi4.setText(_translate("MainWindow", "Psi"))
        self.label_Psi6.setText(_translate("MainWindow", "Psi"))
        self.label_FLText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#005500;\">Front Left</span></p></body></html>"))
        self.label_FRText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#005500;\">Front Right</span></p></body></html>"))
        self.label_RLOText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#005500;\">Rear Left Outer</span></p></body></html>"))
        self.label_RLIText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#005500;\">Rear Left Inner</span></p></body></html>"))
        self.label_RRIText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#005500;\">Rear Right Inner</span></p></body></html>"))
        self.label_RROText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#005500;\">Rear Right Outer</span></p></body></html>"))
        self.label_Text_TPMS.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#0055ff;\">Tyre Pressure Management System</span></p></body></html>"))
        self.pushButton_Done.setText(_translate("MainWindow", "Done"))
        self.label_BusNoText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">Bus Number :</span></p></body></html>"))

import xz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

